name: action_log_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  http: ^1.5.0
  iconsax_plus: ^1.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/presentation/assets/images/
