name: action_log_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.7.0

environment:
  sdk: ^3.9.0

dependencies:
  connectivity_plus: ^7.0.0
  get: ^4.7.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  http: ^1.5.0
  iconsax_plus: ^1.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  mime: ^2.0.0
  http_parser: ^4.1.2
  image_picker: ^1.2.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/presentation/assets/images/

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-dir: lib/gen_l10n
  output-localization-file: app_localizations.dart